services:
  mucheroo:
    container_name: mucheroo
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres

  postgres:
    container_name: pg-local
    user: root
    image: docker.io/bitnami/postgresql:16
    restart: always
    volumes:
      - ./data/pg-local:/bitnami/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
