services:
  mucheroo:
    container_name: mucheroo
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    user: root
    ports:
      - 5432:5432
    image: docker.io/bitnami/postgresql:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      disable: false
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
    volumes:
      - ./data/pg-local:/bitnami/postgresql/data